#---- GENERAL
GPU: 0
VERBOSE: True

#---- PATHS
MODEL_DIR: 'bin_lstm/'
RESULTS_DIR: 'results_lstm/'
LOG_DIR: 'logs/'
MODEL_NAME: 'lstm'

#---- DATASET
# SPLITS: 3
# FOLDS: 10
# SEEDS: [11331] #, 11435, 12123, 53453, 42344, 24234, 65747, 84443, 29345, 99543]
# VAL_SIZE: 0.1
# FRAMES: 64
# CHANNELS: 4
# DATASET: 'openpose'
# openpose:
#     KEYPOINTS: 13
# posenet:
#     KEYPOINTS: 17
# CLASSES: 31
# LABELS: ['standing','check-watch','cross-arms','scratch-head','sit-down','get-up','turn-around','walking','wave1','boxing',
#          'kicking','pointing','pick-up','bending','hands-clapping','wave2','jogging','jumping','pjump','running']


### Dataset
dataset: 'smarthome'
features: 'skeleton'
skeleton:
    
    pose: 'alphapose'

rgb: 
    backbone: 'raw'
    

fusion:
    pose: 'alphapose'

    backbone: 'raw'


    arch: 'Cross-Attention-POSERGB-BERT'

evalutaion: 'CO'

CO:
    CLASSES: 3

CV1:
    CLASSES: 19


### Saved Result Pickle

Result_dire: 'Result'



#---- AUGMENTATION
FLIP_P: 0.5
RN_STD: 0.03





#---- MODEL
PATCH_SIZE: 1
MODEL_SIZE: 'X4'

X1:
    N_HEADS: 16
    N_LAYERS: 1
    EMBED_DIM: 256
    DROPOUT: 0.4
    MLP: 512





X2:
    N_HEADS: 64
    N_LAYERS: 4
    EMBED_DIM: 256
    DROPOUT: 0.4
    MLP: 512



    
X3:
    N_HEADS: 256
    N_LAYERS: 1
    EMBED_DIM: 256
    DROPOUT: 0.4
    MLP: 512

X4:
    N_HEADS: 512
    N_LAYERS: 1
    EMBED_DIM: 256
    DROPOUT: 0.4
    MLP: 512


resnet18:
    N_HEADS: 64
    N_LAYERS: 1
    EMBED_DIM: 256
    DROPOUT: 0.4
    MLP: 512



no_lstm_X4:
    N_HEADS: 256
    N_LAYERS: 1
    EMBED_DIM: 256
    DROPOUT: 0.4
    MLP: 512

no_lstm_X3:
    N_HEADS: 64
    N_LAYERS: 1
    EMBED_DIM: 256
    DROPOUT: 0.4
    MLP: 512


no_lstm_X2:
    N_HEADS: 32
    N_LAYERS: 1
    EMBED_DIM: 256
    DROPOUT: 0.4
    MLP: 512



no_lstm_X1:
    N_HEADS: 8
    N_LAYERS: 1
    EMBED_DIM: 256
    DROPOUT: 0.4
    MLP: 512


#---- TRAINING SETTINGS 
N_EPOCHS: 65   
BATCH_SIZE: 8
WEIGHT_DECAY: 0.000001  
WARMUP_PERC: 0.4  
STEP_PERC: 0.8

#---- RANDOM SEARCH
N_TRIALS: 5
