#---- GENERAL
GPU: 0
VERBOSE: True

#---- PATHS
MODEL_DIR: 'bin/'
RESULTS_DIR: 'results/'
LOG_DIR: 'logs/'
MODEL_NAME: 'BERT'







### Dataset
dataset: 'smarthome'
features: 'fusion'
skeleton:
    
    pose: 'alphapose'

rgb: 
    backbone: 'resnet152' ## Extracted features used from pretrained resnet152
    

fusion:
    pose: 'alphapose'

    backbone: 'resnet152'


    arch: 'SSR-BERT'

evalutaion: 'CD3'

CO:
    CLASSES: 3

CD1:  # Train on smarthome and tested on ETRI-ACTIVITY 3D
    CLASSES: 4

### Saved Result Pickle

Result_dire: 'Result'



#---- AUGMENTATION
FLIP_P: 0.5
RN_STD: 0.03





#---- MODEL
PATCH_SIZE: 1
MODEL_SIZE: 'no_lstm_X2'




X1:    
    N_HEADS: 96
    N_LAYERS: 1
    EMBED_DIM: 128
    d_model: 256
    DROPOUT: 0.125
    MLP: 256

X2:    
    N_HEADS: 128
    N_LAYERS: 1
    EMBED_DIM: 128
    d_model: 256
    DROPOUT: 0.125
    MLP: 256

X3:    
    N_HEADS: 256
    N_LAYERS: 1
    EMBED_DIM: 128
    d_model: 256
    DROPOUT: 0.125
    MLP: 256

LSTM:    
    N_HEADS: 64
    N_LAYERS: 1
    EMBED_DIM: 128
    d_model: 256
    DROPOUT: 0.15
    MLP: 256

    

no_lstm_X2:    
    N_HEADS: 128
    N_LAYERS: 1
    EMBED_DIM: 128
    d_model: 256
    DROPOUT: 0.125
    MLP: 256


no_lstm_X1:    
    N_HEADS: 96
    N_LAYERS: 1
    EMBED_DIM: 128
    d_model: 256
    DROPOUT: 0.125
    MLP: 256













#---- TRAINING SETTINGS 
N_EPOCHS: 225
BATCH_SIZE: 512
WEIGHT_DECAY: 0.00001  
WARMUP_PERC: 0.4  
STEP_PERC: 0.8
REG_FACTOR: 0.15                          

#---- RANDOM SEARCH
N_TRIALS: 25
